# Elixir
export ERL_AFLAGS="-kernel shell_history enabled"

# C and C++
CXXFLAGS="-std=c++20 -Wall -Wextra -Wpedantic -Werror -Weffc++"
alias g++="g++-13 $CXXFLAGS"
alias gcc="gcc-13"

# Homebrew
if [[ $(uname -m) == 'arm64' ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# GPG
$ if [ -r ~/.zshrc ]; then
    echo -e '\nexport GPG_TTY=$(tty)' >> ~/.zshrc;
else
    echo -e '\nexport GPG_TTY=$(tty)' >> ~/.zprofile;
fi

