# Bat aliases
alias fp='fzf --preview "bat --style numbers,changes --color=always {}" | head -500'

# Because macOS keeps rewriting /etc/zshrc after every update, it keeps breaking nix
# setup. We have to manually restore the confguration here.
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  NIXPATH=$(
    env -i HOME="${HOME}" USER="$USER" sh -c '
      source /etc/static/zshenv
      echo "${PATH}"
      '
  )
  PATH+=${NIXPATH}
fi
