tap "homebrew/bundle"
tap "homebrew/services"
brew "stow"
brew "wget"
brew "broot"
brew "bat"
brew "gcc"
brew "clang-format"
brew "cppman"
brew "libpq", link: true
brew "md5sha1sum"
brew "ripgrep"
brew "tcpflow"
brew "tree"
cask "alacritty"
