tap "homebrew/bundle"
tap "homebrew/services"
tap "sdkman/tap"
brew "stow"
brew "wget"
brew "broot"
brew "bat"
brew "gcc"
brew "clang-format"
brew "cppman"
brew "delve"
brew "fzf"
brew "ghcup"
brew "libpq", link: true
brew "md5sha1sum"
brew "neovim", args: ["HEAD"]
brew "nvm"
brew "pyenv"
brew "ripgrep"
brew "tcpflow"
brew "tree"
brew "sdkman/tap/sdkman-cli"
cask "alacritty"
