# Change leader
set -g prefix C-f

# Set vim-like pane switching and resizing  
setw -g mode-keys vi

bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# Unbind old movement keys
unbind Up     
unbind Down   
unbind Left   
unbind Right  

unbind C-Up   
unbind C-Down 
unbind C-Left 
unbind C-Right

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# Rename current window
bind-key E command-prompt -I "rename-window "

# Kill current session
bind-key K confirm-before -p "kill-session? (y/n)" kill-session

# split panes using | and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'niksingh710/minimal-tmux-status'

# Initialize TPM (should always be the last line)
set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin:/usr/sbin:/sbin"
run '/opt/homebrew/opt/tpm/share/tpm/tpm'
