InlayHints:
  Enabled: Yes
  ParameterNames: No
  DeducedTypes: Yes
  TypeNameLimit: 15
  Designators: No
CompileFlags:
  Add:
    - -std=c++20
    - -Wall
    - -Wextra
    - -Werror
    - -Weffc++
    - -pedantic
    - -Wno-unused-variable
    - -Wno-unused-parameter
    - -Wno-unused-function
    - -Wno-unused-but-set-variable
    - -Wno-unused-local-typedefs
    - -Wno-unused-value
